config/routes.rb
Rails.application.routes.draw do
  resources :roles
  devise_for :users
  scope "/admin" do
     resources :users
    end
  resources :categories
  resources :articles
  resources :comments

  root 'categories#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

	belongs_to :category
	has_many :comments
	belongs_to :user 

    validates_presence_of :title, :body, :category_id, :publish_date
    validates_numericality_of :category_id, greater_than: 0
    validates_length_of :body, minimum: 10
    validates_length_of :title, minimum:3
    
	validate :check_based_on_date

	def check_based_on_date
		if !self.publish_date.nil?
			if self.publish_date < Date.today
				self.errors.add(:publish_date, "Article should not be less than today date")
            end
        end
    end
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   
   # this method is responsible for invoking ability.rb after before_action :authenticate_user! 

    load_and_authorize_resource
    
    def index
        @articles = Article.paginate(:page => params[:page], :per_page => 10)
    end

    def new
        @article = Article.new
        @category = Category.new
    end


    def create
        @article = Article.new(article_params)
        @article.user_id = current_user.id 
        
        if @article.save
            redirect_to article_path(@article.id), notice: "Successfully created #{@article.title}"
        else
            render action: "new"
        end
    end 


    def show
        begin
           @article = Article.find(params[:id])

           @comment = Comment.new 
        rescue ActiveRecord::RecordNotFound
           redirect_to articles_path, notice: "Record not found"
       end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        previous_name = @article.title
        if @article.update_attributes(article_params)
            redirect_to article_path(@article.id), notice: "Successfully updated"
        else
            render action: "edit"
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path, notice: "Successfully deleted #{@article.title}"
    end

    private
  
    def article_params
       params[:article].permit(:title, :body, :category_id, :publish_date)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	
  <%if @article.errors.any? %>
  <h3>Errors</h3>
  <ul>
	<% @article.errors.full_messages.each do |msg| %>
	<li> <%=msg %> </li>
  <% end %>
  </ul>
  <% else %>
   <div class="form-group">
	<%= f.label :category, "Category" %>
	<%= f.collection_select :category_id,Category.all, :id ,:name, {prompt: "select category"}, {class: "form-control"} %> <br/>
	</div>
	
	<div class="form-group">
	<%= f.label :title, "Title" %>
	<%= f.text_field :title, class: "form-control" %> <br/>
	</div>
	
	<div class="form-group">
	<%= f.label :body, "Body" %>
	<%= f.text_area :body, class: "form-control" %> <br/>
	</div>
	
	<div class="form-group">
	<%= f.label :publish_date, "Publish Date" %>
	<%= f.text_field :publish_date, class: "form-control" %> <br/>
	</div>
	
	
	<%= f.submit "Submit", class: "btn btn-info" %>

  <% end %>

<% end %>

<script>
$(document).ready(function(){
	$('#article_category_id').chosen();
});
</script>

app/views/articles/edit.html.erb

<h3>Update Article</h3>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="row">
   <!-- Blog Entries Column -->
   <div class="col-md-8">
       <h1 class="page-header">
           Listing Articles
       </h1>
       <% @articles.each do |article| %> 
       <!--  Blog Post -->
       <h2>
           <%= link_to article.title, article_path(article.id) %>
       </h2>
       <p class="lead">
           in <%= link_to article.category.name, category_path(article.category_id) %> 
       </p>
       <p><span class="glyphicon glyphicon-time"></span> Posted on <%= article.created_at.strftime("%B %d, %Y at %H:%M %p (UTC)") %> </p>
       <hr>
       <img class="img-responsive" src="http://placehold.it/900x300" alt="">
       <hr>
       <p>
         <%= article.body.truncate(200) %>
       </p>
      
       <%= link_to article_path(article.id), class: "btn btn-primary" do %>
          Read More <span class="glyphicon glyphicon-chevron-right">
       <% end %>
       <hr>
       <% end %>
       <!-- Pager -->
       <ul class="pager">
           <li class="previous">
               <a href="#">&larr; Older</a>
           </li>
           <li class="next">
               <a href="#">Newer &rarr;</a>
           </li>
       </ul>

   </div>

   <!-- Blog Sidebar Widgets Column -->
   <div class="col-md-4">
       <!-- Blog Search Well -->
       <div class="well">
           <h4>Blog Search</h4>
           <div class="input-group">
               <input type="text" class="form-control">
               <span class="input-group-btn">
                   <button class="btn btn-default" type="button">
                       <span class="glyphicon glyphicon-search"></span>
               </button>
               </span>
           </div>
           <!-- /.input-group -->
       </div>

       <!-- Blog Categories Well -->
       <div class="well">
           <h4>Blog Categories</h4>
           <div class="row">
               <div class="col-lg-6">
                   <ul class="list-unstyled">

                      <% Category.all.each do |category| %>
                       <li><%= link_to category.name, category_path(category.id) %>
                       </li>
                       <% end %>
                   </ul>
               </div>
              
           </div>
           <!-- /.row -->
       </div>

       <!-- Side Widget Well -->
       <div class="well">
           <h4>Side Widget Well</h4>
           <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
       </div>

   </div>
</div>

<%= will_paginate @articles %>


<% if can? :create, Article.new %>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<div class="row">
   <div class="col-md-8">
      <div class="page-header">
        <h2>Add Article</h2>
      </div>
      <%= render 'form' %>
    </div>


 <div class="col-md-4">
    <div class="page-header">
      <h2> Add Category </h2>
    </div>
    <%#= render './categories/form' %>

    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Add Category
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Category</h4>
      </div>
      <div class="modal-body">
        <%= render './categories/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
    <div class="page-header">
      <h2>Categories</h2>
   </div>

   <ul class="list-group">
      <% Category.all.each do |category| %>
         <li class="list-group-item">
           <span class="badge"><%= category.articles.size%></span>
           <%= category.name %>
         </li>
      <% end %>
   </ul>
 </div>
</div>

app/views/articles/show.html.erb
<div class="row">
            <!-- Blog Post Content Column -->
<div class="col-md-8">
    <!-- Blog Post -->
    <!-- Title -->
    <h1><%= @article.title %></h1>

    <!-- Author -->
    <p class="lead">
        in <%= link_to @article.category.name, category_path(@article.category_id) %>
    </p>

    <hr>

    <!-- Date/Time -->
   <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @article.created_at.strftime("%B %d, %Y at %H:%M %p (UTC)") %> </p>

    <hr>

    <!-- Preview Image -->
    <img class="img-responsive" src="http://placehold.it/900x300" alt="">

    <hr>

    <!-- Post Content -->
   
    <p>
      
      <%= @article.body %>
    </p>

    <hr>

    <!-- Blog Comments -->

  

    <!-- Posted Comments -->

    <!-- Comment -->
 <div id="articleComments">
    <%= render './comments/comments' %>
</div>

      <!-- Comments Form -->
    <div class="well">
      <h4>Leave a Comment:</h4>

        <% @comment = Comment.new %>

        <% if user_signed_in? %>
          <%= render '/comments/form' %>
        <% else %>
          <h5>Login to add a comment</h5>
        <% end %>
                           
    </div>

    <hr>

</div>

<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
    <!-- Blog Search Well -->
    <div class="well">
        <h4>Blog Search</h4>
        <div class="input-group">
            <input type="text" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">
                    <span class="glyphicon glyphicon-search"></span>
            </button>
            </span>
        </div>
        <!-- /.input-group -->
    </div>

    <!-- Blog Categories Well -->
    <div class="well">
        <h4>Blog Categories</h4>
        <div class="row">
            <div class="col-lg-6">
                <ul class="list-unstyled">
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-6">
                <ul class="list-unstyled">
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->
    </div>

    <!-- Side Widget Well -->
    <div class="well">
        <h4>Side Widget Well</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
  

<% if can? :update, @article %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>


<%= link_to 'Back', articles_path %>