config/routes.rb
Rails.application.routes.draw do
  resources :roles
  devise_for :users
  scope "/admin" do
     resources :users
    end
  resources :categories
  resources :articles
  resources :comments

  root 'categories#index'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">My Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <% if can? :read, Article.new %>
           <%= raw(controller.controller_name == "articles" ? "<li class='active'>" : "<li>") %>
           <%= link_to "Articles", articles_path %></li>
        <%end%>

        <% if can? :read, Category.new %>
           <%= raw(controller.controller_name == "categories" ? "<li class='active'>" : "<li>") %>
           <%= link_to "Categories", categories_path %></li>
        <%end%>


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <% Category.all.each do |category| %>
               <li><%= link_to category.name, category_path(category.id) %> </li>
            <% end %>

          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
          <ul class="dropdown-menu">
           
            <% if can? :read, Role.new %>
                <%= raw(controller.controller_name == "roles" ? "<li class='active'>" : "<li>") %>
                <%= link_to "Roles", roles_path %></li>
            <%end%>   

            <% if can? :read, User.new %>
                <%= raw(controller.controller_name == "users" ? "<li class='active'>" : "<li>") %>
                <%= link_to "Users", users_path %></li>
            <%end%>  

          </ul>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://harvesthq.github.io/chosen/chosen.css">
  <link rel="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src = "https://cdnjs.cloudflare.com/ajax/libs/chosen/1.7.0/chosen.jquery.min.js"> </script>

  <script src = "//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<% if user_signed_in? %>
Welcome <%= current_user.email %> <%= link_to "Account setting", edit_user_registration_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>

<% else %>

<%= link_to "Login", new_user_session_path %> | <%= link_to "Sign up", new_user_registration_path %>
<% end %>
<br/>

<%= render "./layouts/navbar" %>
<%= link_to "comments", comments_path %> | <%= link_to "Roles", roles_path %>
<br/>

<%= notice %>
<%= alert %>

<%= yield %>
</div>
</body>
</html>